/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const priorityCardinality_Logic = require('./code/priorityCardinality-logic');
const fetchClosedTickets_Logic = require('./code/fetchClosedTickets-logic');

class hrsassistSrv extends LCAPApplicationService {
    async init() {

        this.on(['READ', 'UPDATE'], 'Ticket', async (request, next) => {
            await priorityCardinality_Logic(request);
            return next();
        });

        this.before(['CREATE', 'UPDATE'], 'KnowledgeBase', async (request) => {
            await fetchClosedTickets_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    hrsassistSrv
};